### ISSUE TITLE
Deploying while ember serve is running

### ISSUE THREAD

**Issue by marcoow** [ember-cli/ember-cli-deploy#134]
I just discovered an edge case which is probably quite likely to happen though. When you're deploying an application and also have `ember serve` running for the same project at the same time you might not be deploying the actual files in `dist` that were built by the deployment but actually files that `ember serve` builds at the same time or after the build process that was triggered by `ember deploy`.

In my case that resulted in `ember deploy --environment staging` actually deploying the development assets (including for development `index.html` with references to e.g. `<script src="/ember-cli-live-reload.js" type="text/javascript"></script>` which of course doesn't exist in the staging env that had `"buildEnv"` configured as `"staging"`).

I think a solution for that would be to use `ember build`'s `--output-path` option for the build process and point that to some temporary dir and then deploy the files from there.

**Comment by achambers** [comment]
Thanks for that @marcoow.  Yep, that sounds like the logical fix. Thanks for raising

**Comment by blimmer** [comment]
Thanks for the heads up @marcoow , I think we've just been lucky and not hit this yet while deploying.

**Comment by quiddle** [comment]
:+1: This has bitten me.

**Comment by johnnyshields** [comment]
:+1: this has bitten me too and I raised it as an Ember CLI issue 9 months ago: https://github.com/ember-cli/ember-cli/issues/1683

**Comment by bradplank** [comment]
I was looking into fixing this issue, and wondered what other would prefer as a solution.  I had 2 options is mind:
1) Simple change the outputPath to something like `dist-deploy`
2) Add the outputPath to the config.js file, and make it configurable

I think options 2 is the better solution, any other suggestions?

**Comment by quiddle** [comment]
I think if we leave the setting to be configured separately, people will only discover it after they've already made the mistake. I can't think of a reason why it shouldn't deploy from a dedicated directory by default. Is there any reason not to deploy from a dedicated directory? You could still make the configure option, which would let people use 'dist' if they need it.

**Comment by bradplank** [comment]
I agree, maybe a combination of both options where the outputPath is configurable, but defaults to `dist-deploy`?  I think that seems very reasonable as well.

**Comment by johnnyshields** [comment]
I think this should be solved by Ember-CLI itself. It's not specific to this plugin.

**Comment by LevelbossMike** [comment]
@bradplank  This can be changed by changing the build-options in the deploy-command

This uses the ember-cli build command internally so I think that's the cleanest solution

https://github.com/ember-cli/ember-cli-deploy/blob/master/lib/commands/deploy.js#L31

Anyone who wants to contribute this to the project? Otherwise I'll change this in the next days.

**Comment by marcoow** [comment]
I don't actually think it's great to use e.g. `dist-deploy` as you would have to add that directory to `.gitignore` as well then. I'd say deploying shouldn't modify the project directory at all so using a folder in the system's tmp dir is much better.

**Comment by bradplank** [comment]
What if the dist-deploy directory was created for deployment then removed as part of the deploy action?  That seems reasonable to me.

**Comment by marcoow** [comment]
@bradplank: I don't see how that's better than using a temporary directory that wouldn't need to be cleaned up in the first place.

**Comment by bradplank** [comment]
If we can come up with a good solution as a group, I would be happy to make the modifications.  Any ideas are always welcome, and build a better solution.

**Comment by blimmer** [comment]
I agree with @marcoow that not requiring modification of the `.gitignore` would be ideal. I think it's better to, by default, write out to the `tmp` directory since it's already in the default ember-cli [gitignore](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/gitignore).

In some circumstances, I could see the after deploy hook not appropriately removing the `dist-deploy` folder (a crash or something) and people accidentally checking in the folder to their scm. This happens to me all the time with [ember-cli/broccoli](https://github.com/broccolijs/broccoli/issues/187) and we're still trying to figure out why.

For that reason, I would suggest: 
* Always try to remove the built files after deploy
* Use `tmp/` directory by default
* Allow configuration to use another root level directory (e.g. `dist-deploy`)

**Comment by duizendnegen** [comment]
This issue can be closed
