### ISSUE TITLE
Specify key names for index.html Redis value

### ISSUE THREAD

**Issue by Jellyfishboy** [ember-cli/ember-cli-deploy#151]
Apologies if this has been asked before, but I can't seem to find anything in relation to this topic.

Is there any way to specify the key name for the index.html Redis value? I would like several apps to point to different HTML and asset files in Redis.

For example, currently my key value is the following:

my-app:322c13

How would I define it like so:

demo-app:322c13
stage-app:322c13
production-app:322c13

Thanks

**Comment by LevelbossMike** [comment]
This is currently not supported by ember-deploy-redis as this defaults to the project name. The new pipeline way of deployments should make it easy to customize this in the future though.

**Comment by LevelbossMike** [comment]
If you want to do this with the current version you'd need to change the way the taggingAdapter is initialized.

https://github.com/ember-cli/ember-cli-deploy/blob/master/lib/tasks/deploy-index.js#L32

You need to make sure that the config.manifest is passed in instead of the manifest directly. This also needed to be changed in the list task.

Happy to accept a PR for that :)

**Comment by Jellyfishboy** [comment]
I understand this may not be supported by **ember-deploy-redis**, but why close the issue? One of the reasons for issues is to raise potential improvements or new features to a codebase, and allow users to submit PRs and comments around the related topic...

**Comment by LevelbossMike** [comment]
Sorry for the quick close. Happy to discuss this further if you need help for PRing this.

I also added an `easy-contribution`-label.
