### ISSUE TITLE
Store and Assets by SSH

### ISSUE THREAD

**Issue by gitowiec** [ember-cli/ember-cli-deploy#153]
I have a request for simple deploy by SSH. I wanted to use **ember-deploy-ssh-index** but as I understood its manual, it only supports to upload index.html. I need to upload all files from dist/ to my server. The best option could be uploading sources and running 'ember build' remote.

**Comment by LevelbossMike** [comment]
Assets are uploaded via asset-adapters. There are multiple available to do this but most commonly you'd upload your asset files to something like amazon s3 or rackspace cloudfiles with a cdn in front. I am not aware if anybody has written a filesystem uploader for assets. It should be easy to do if not but I doubt it has any benefit over using s3 or similiar services.

**Comment by gitowiec** [comment]
Yes, it has benefits, it is not amazon or anything you don't own. For me it would be a start, not some cloud I don't know who it owns, where it is located and under what law. That's my point of view. But if ember-cli-deploy is formal way of deploying Ember-cli application, it should contain such primitive and base adapters. What I mean is commonly uploading files to amazon s3 (or whatever cloud is there) is region dependend. And another thing, if one is like I, just at the beginning of the whole 'getting know with ember', it is unnecessary hustle of getting into knowing with some cloud service I am not gonna use.

**Comment by LevelbossMike** [comment]
Well I get the "I don't like cloud because of legal situation being unclear" argument but in the realm of deploying ember application this is kind of unintuitive for me. You likely want to deploy your application to a public audience so you most likely don't have any 'secret' assets that you don't want to be available in the public realm.

That's most likely the reason why there isn't a filesystem asset adapter for deploying assets to a server filesystem yet (at least none that I am aware of). You can check emberobserver.com if there is something like that available. If there isn't something like that it will be most likely be easy to do if you really have the need for something like that.

You can have a look at the [custom-adapter](https://github.com/ember-cli/ember-cli-deploy#custom-adapters) section on how one would write an asset adapter that can do this.

**Comment by treyhunner** [comment]
@gitowiec someone forked ember-deploy-ssh-index and made [ember-cli-deploy-ssh][] for serving all assets over SSH

[ember-cli-deploy-ssh]: https://github.com/eddflrs/ember-cli-deploy-ssh

**Comment by MarkMT** [comment]
Wow great timing @treyhunner - I was just wondering about this myself.

**Comment by gitowiec** [comment]
@treyhunner  thanks for informing! I don't mind this right now, because I just run `ember build` locally, zip folders and drop it onto Azure Windows Server VM through Remote Desktop. This is the simplest way, no need of any configuration.

**Comment by Envek** [comment]
I have another reason to be able to deploy via SSH: we are making application that will work in customer's closed network — end users wouldn't have access to Internet at all. So application MUST be fully self-contained.

**Comment by ghedamat** [comment]
@Envek 0.5.0 should be released in the next week and it's already in available in beta

it should be fairly straightforward to build a plugin that uploads all the assets and the `index.html` over an ssh connection

you can look at the new documentation here
http://ember-cli.github.io/ember-cli-deploy/docs/v0.5.x/writing-a-plugin/

and feel free to ping us on the ember community slack channel `#ember-cli-deploy` if you need any help/guidance!

**Comment by lukemelia** [comment]
Closing for now. Looking forward to this plugin. :+1:
