### ISSUE TITLE
Why is deploy:index and deploy:assets deprecated?

### ISSUE THREAD

**Issue by ianwalter** [ember-cli/ember-cli-deploy#200]
I actually use `deploy:index` so that I can deploy my index file in development without having to deploy assets. How should I do this going forward?

**Comment by lukemelia** [comment]
@ianwalter create a `development` deployTarget and specify via configuration that you only want to run certain plugins. Then you can deploy using `ember deploy development`. An example can be found in https://github.com/lukemelia/ember-cli-deploy-lightning-pack/blob/master/blueprints/lightning-deploy-config/files/config/deploy.js

Does that address your scenario?

**Comment by ianwalter** [comment]
That configuration looks very different. Is my deploy.js configuration old? I'm using ember-cli-deploy 0.4.3 and my configuration looks like this:

```js
module.exports = {
  development: {
    buildEnv: 'development',
    store: {
      // ...
    }
  }
}
```

The configuration you referenced looks like it would address my scenario though so feel free to close.

**Comment by achambers** [comment]
@ianwalter The example @lukemelia mentioned is indeed for v0.5.0+. It has changed quite considerably. The reason why the commands you mentioned are deprecated is because ember-cli-deploy has taken a considerable architectural change from v0.5.0+ and as such the commands will work differently.

As @lukemelia mentioned, you will be able to do as you need to, it'll just be done in a different way than calling those two commands.

Does that answer your questions?

**Comment by ianwalter** [comment]
Right, yes it does, thanks!

**Comment by rchrd2** [comment]
What would be the equivalent values to put in `plugins: [ ]` to only upload the assets? Ie, what is the substitute for `ember deploy:assets`? Thanks.
