### ISSUE TITLE
Undeploy, Delete, Remove

### ISSUE THREAD

**Issue by angelosarto** [ember-cli/ember-cli-deploy#289]
Is there a command for undeploy?  
I can remove the key from redis (since I am using the redis plugin for the index)  but that still leaves behind the assets in s3.

**Comment by duizendnegen** [comment]
There's not at the moment - for purging assets from S3 and similar we reasoned that hosting was cheap enough to not really bother until it became a burden. The challenge here is that there is no good way to tell whether a revision you'd want to delete contains assets that other revisions that you want to keep don't. Possibly a versioned manifest file (https://github.com/ember-cli-deploy/ember-cli-deploy-manifest) could help out.

**Comment by lukemelia** [comment]
@angelosarto do you have a particular use case that demands this, or are you just curious?

**Comment by angelosarto** [comment]
More curious than a specific use case.
I agree with the reasoning that hosting is so cheap that the storage of the old file is unlikely to ever be an issue.
I think I ran into this more in Dev and just wanting to clean-out old versions.

**Comment by marcoow** [comment]
We actually have a use case for this. We have a staging system that we deploy branches to and use the branch name as revision identifier so that the app is accessible as e.g. https://example.com/index.html:branch. Whenever the branch is fully tested we merge it back to master and deploy. Whenever we do that I'd like to be able to delete the respective deployment from our staging system so nobody is accidentally accessing that anymore.
