### ISSUE TITLE
Implement fetchInitialRevisions for appropriate plugins

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli-deploy#338]
- [x] ember-cli-deploy-redis
- [x] ember-cli-deploy-s3-index
- [x] ember-cli-deploy-azure-tables

Others?

see: https://github.com/ember-cli/ember-cli-deploy/pull/323#issuecomment-164784993

**Comment by seawatts** [comment]
woo hoo! :+1: Can't wait =)

**Comment by ghedamat** [comment]
@lukemelia going back to #323 and the code in ember-cli-deploy-redis and ember-cli-deploy-display-revisions it looks like we decided to implement `fetchInitialRevisions` and `fetchRevisions` so that they return a `revisionData` property but in the current version we use a `revisions` property instead that is expected to be an Array

I'm thinking maybe we should move to the hooks returning data like this

```
revisionsData: {
   initials: [ ... ],
   revisions: [ ... ]
}
```

and update also the display-revisions-plugin, plus all the other plugins that implement the hooks.

we could also keep the old `revisions` key for a while and add a deprecation to display-revisions

thoughts?

**Comment by lukemelia** [comment]
While writing 0.6.x docs, I rethought this a little (see results at http://ember-cli.com/ember-cli-deploy/docs/v0.6.x/pipeline-hooks/)

```
fetchInitialRevisions -->  returns an object (or a promise resolving to
                           one) that has an `initialRevisions` property
                           whose value is an array of revision objects.[1]
                           i.e. `{ initialRevisions: [...] }`
```

and

```
            \- fetchRevisions  returns an object (or a promise resolving
             \                 to one) that has a `revisions` property
              \                whose value is an array of revision
               \               objects.[1] i.e. `{ revisions: [...] }`
```
