### ISSUE TITLE
Support a base .env.deploy file

### ISSUE THREAD

**Issue by blimmer** [ember-cli/ember-cli-deploy#341]
Right now, you have to have a separate .env file for each environment. It would be nice to provide default, or shared secrets in a `.env.deploy` file without specifying an environment.

Imagine if your development and staging s3 access keys are the same, right now you have to symlink or copy/paste the file.

I propose the following solution:
1. we load up the `.env.deploy` file
2. we load up the `.env.deploy.<target-environment>` file (keys in here would override the higher level file).

Thoughts?

**Comment by achambers** [comment]
Sounds reasonable to me. If we're going for an environment agnostic file should we just use `.env` instead of `.env.deploy`?

I can see a world where you might have S3 credentials for your app and your deploy. 

Then if you want to specify deploy environment specific ones you can use the current files?

**Comment by blimmer** [comment]
I like that. PR on the way.
