### ISSUE TITLE
Pass --target as the build target default

### ISSUE THREAD

**Issue by danshultz** [ember-cli/ember-cli-deploy#48]
I know there is `buildEnv` for the deployment config. I think it would make sense to default `buildEnv` to the `--target` option being provided.

Does this change make sense or am I missing a common usage?

I can create a PR if this is a reasonable change

**Comment by LevelbossMike** [comment]
The reasoning behind defaulting to `production` was that it does not make much sense to upload an ember-cli app without running a production like build before deploying anywhere.

But one would most likely want this behaviour when using any other environment than development. for example `--environment staging` or `--environment pre-production`.

Actually using development environment does not make much sense when deploying anyway so it will be most likely the correct assumption to default to the passend environment and one should be able to override this in `deploy.js`.

**Comment by lukemelia** [comment]
I wonder if we should avoid using `--environment` for this reason. It's confusing that I would specify an environment on the command line and have it not actually be the environment that ember-cli is using to build. Perhaps `--deploy-target` of `--deploy-to` would be clearer?

**Comment by LevelbossMike** [comment]
Well most likely you will build/deploy the environment that you passed to `--environment`. The only special case is `development` which doesn't make much sense anyway other than testing out your settings when setting up a deployment pipeline.

I like the `--environment` because it mirrors `ember-cli`'s behaviour which kind of makes sense for an `ember-cli`-addon. Not totally opposed to renaming though.

**Comment by danshultz** [comment]
I do like the name `--environment ` and I think it makes sense to default to production as that is the common use case. To alleviate confusion due to naming, I think it should be passed through as the build environment because if a person is deploying to multiple environments, it would be common to have different config for the build. 

Since by default the "build type" of production is dependent on the environment being set to production in ember CLI, it's up to the use to carve their own path for what they want for their builds in other environments.

I also think that it would be common to have a different config for each environment and it would make sense to carry this across the deploy plugin for consistency.

A different question however, does it make sense to tightly couple the deploy to and the environment? I think it does.

I've pondered if it would make sense to explicitly split the concept of build type from the environment in ember CLI but am not sure that's a common use case for people.

**Comment by danshultz** [comment]
Of course, with leaving the feature of `buildEnv` it provides a person the option of still specifying their build env directly in their deploy config if they decided to have multiple deploys with a common env, although I cannot think of a use case as smoke testing is easily supported with `ember-cli-deploy`

**Comment by lukemelia** [comment]
I think we will benefit from having the ability to vary deployment profile
independently from build environment. Example: deploying a few copies of
the production build of an app to different data centers around the globe,
or to different partner sites.

How about `ember deploy foo (no flag) would mean use the deploy.js section
named "foo" and that section could specify an environment property to
specify the build environment? If the property is left out, environment
would default to the target name.

An issue to consider related to this: it is not easy to do a true staging
build with ember-cli. In particular, in ember-cli, "production" builds are
special-cased to use the stripped ember.prod.js. I want that kind of build
in my staging deploys because I want my staging deploys to be faithful to
my production deploys. Perhaps we should figure out how to allow this to be
customized in ember-cli and then provide the ability to set this in the
deploy configuration.

**Comment by quiddle** [comment]
I like @lukemelia's suggestion of named sections in deploy.js. What would the default behavior of `ember deploy` be? As in, which named section would be deployed if no argument was passed?

**Comment by lukemelia** [comment]
I think it is reasonable to require the user to be explicit about the deploy target. In the case of bare `ember deploy`, we could print an error that includes a list of the configured deploy targets.

**Comment by quiddle** [comment]
Or perhaps a prompt to select a target?

**Comment by achambers** [comment]
I'm not convinced a prompt is the way to go. What happens when people are
using this in a continuous deployment scenario? It doesn't make sense when
a CI server is potentially running these commands for it to prompt and
wait.

**Comment by quiddle** [comment]
That's a pretty good argument for an error. The scenario I was considering was the out-of-the-box setup for a developer. Being able to drop in a few values and run `ember deploy` would be nice and simple.

How about if there was only one target, it's run by default and if there are multiple targets, throw an error?

**Comment by achambers** [comment]
That sounds feasible to me.

**Comment by lukemelia** [comment]
:+1:

**Comment by danshultz** [comment]
:+1: - I think we all agree that it makes sense that the new interface is `ember deploy <deploy-target, default production>`, e.g. - `ember deploy stage` or `ember deploy:activate production`.

`ember deploy` will default to look for the production "deploy-target"

Since we are going to change the interface of the call, I think this issue is resolved unless anyone else has feedback.

**Comment by lukemelia** [comment]
@danshultz agreed except for 1 bit: `ember deploy` should have default behavior only if there is just a single deploy-target configured. Otherwise it should emit an error with a list of configured deploy targets.
