### ISSUE TITLE
Add redis index deploy features.

### ISSUE THREAD

**Issue by arenoir** [ember-cli/ember-cli-deploy#91]
I have nginx installed with the [HTTP_REDIS](http://wiki.nginx.org/HttpRedis) module so it would be advantageous to have nginx serve the index.html file.  However the nginx redis module is very limited.  It is not easy to lookup the key and then use the key to fetch the content.  

I am thinking a improved approach would be to copy the index content to the value of the current key thus eliminated the need for a lookup.   

The second thing I ran into was wanting to store the html cache.manifest file in redis as well.   I know cache.manifest is a bastard, but it does help with mobile. 

Just wanted to run this by the team. I will most likely fork the ember-deploy-redis repo and implement this functionality.

:beers: to paving the cow paths.

Here is the nginx config; quite simple.

```
map $arg_version $app_version {
    default "current";
    ~^\w+ $arg_version;
}
upstream redisbackend{
    server 127.0.0.1:6379;
}
server {
    location / {
        set $redis_key my-app:$app_version;
        redis_pass redisbackend;
        default_type text/html;
    }
}

**Comment by arenoir** [comment]
Any one have any thoughts about the cache.manifest?

**Comment by lukemelia** [comment]
Hi @arenoir... I think having the right hooks to support for a cache manifest is a good idea. I don't envy you though -- those things are a pain in the ass to deal with.

Regarding writing the HTML content directly to the "current" key in redis, I would like for it to be easy for you to do this in your own addon. It would definitely not become the default behavior for a redis addon because it eliminates many of the benefits of the addon, such as preview and rollback support.

Stay tuned to #88 and chime in if you think the hooks we are planning will not be sufficient to achieve what you need.

**Comment by arenoir** [comment]
@lukemelia thanks for the reply.  I just pushed a pull request to ember-deploy-redis that allows writing directly to the content current key.  Preview and rollback still work, I just moved where the version number was stored.
