### ISSUE TITLE
ember deploy:activate not working

### ISSUE THREAD

**Issue by rduque1** [ember-cli/ember-cli-deploy#97]
Hello,

I am trying to activate a revision, every time it tells me it is successful but actually it isn't.
Here are the commands i do:

    $ ember deploy:list
    version: 0.1.15
    Could not find watchman, falling back to NodeWatcher for file system events
    
    Last 10 uploaded revisions:

    |    isdb:2207a7b

    # => - current revision

    $ ember deploy:activate --revision isdb:2207a7b
    version: 0.1.15
    Could not find watchman, falling back to NodeWatcher for file system events
    
    Activation successful!
    
    Please run `ember deploy:list` to see what revision is current.

    $ ember deploy:list
    version: 0.1.15
    Could not find watchman, falling back to NodeWatcher for file system events
    
    Last 10 uploaded revisions:
    
    |    isdb:2207a7b
   
    
    # => - current revision

    $ redis-cli -h redishost get isdb:current
    (nil)

Do I do something wrong or is it a bug?

Thanks,

Robin

**Comment by LevelbossMike** [comment]
Hi @rduque1!

I just checked in a test project with the redis adapter. And this works correctly on my side. Are you using the correct settings for `redishost` in `deploy.js`?

**Comment by rduque1** [comment]
Hi @LevelbossMike 

Here is my config I just replaced the keys of aws:

    module.exports = {
	development: {
		store: {
		  host: 'redishost',
		  port: 6379
		},
		assets: {
		  accessKeyId: "key...",
		  secretAccessKey: "key...",
		  bucket: "bucket name..."
		}
	},
	production: {
		store: {
		  host: 'redishost',
		  port: 6379
		},
		assets: {
		  accessKeyId: "key...",
		  secretAccessKey: "key...",
		  bucket: "bucket name..."
		}
	}
    };

The index.html for revision is isdb:2207a7b correctly added in the redis:

    $ redis-cli -h redishost get isdb:2207a7b
    "<!DOCTYPE html>\n<html>\n<head>\n\t<meta charset=\"utf-8\">\n\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n\n\t<link rel=\"shortcut icon\" href=\"/favicon.ico\" />\n\n ....

So i think the redis settings are correct, it just does not work for the current.

**Comment by LevelbossMike** [comment]
I just upgraded my test project to ember-cli 0.2.0 and installed ember-cli-deploy#master. 

My setup:

* ember-cli-deploy#master (because #93 )
* ember-deploy-redis@0.0.2
* ember-deploy-s3@0.0.3

works as expected. The only difference in my setup seems to be the host option, which in my case points to `localhost` not `redishost`. I doubt this makes any difference though because these options are passed as they are to the underlying redis library `ember-deploy-redis` is using. Are you doing anything special with redis? maybe access restrictions? I am not an expert in redis configuration though so I may be missing something obvious.

Which also surprises me is that you can put a key into redis but not update the current key.

**Comment by rduque1** [comment]
Hi @LevelbossMike 

Yesterday was the first time I worked with redis so I really do not know if I am doing something wrong with it. 
But it is working know! I was trying to get the same configuration as you. The first thing I did was to put different redis hosts, and apparently this solved it.

Thanks a lot for the help and this great projects you are providing,

Robin

**Comment by LevelbossMike** [comment]
great to hear it's working now
